---
image: quay.io/ansible/molecule:3.0.2
services:
  - name: docker:dind
    entrypoint: ["dockerd-entrypoint.sh"]

stages:
  - tests

variables:
  GIT_STRATEGY: clone
  # DOCKER_HOST: "tcp://localhost:2375"
  DOCKER_TLS_CERTDIR: ""

.molecule_test:
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
  tags:
    - docker
  before_script:
    - export ROLE_NAME=firewalld
    # - apk update && apk add --no-cache py3-pip
    - python3 -m pip install ansible-lint==4.2.0
    - docker -v
    - python3 --version
    - ansible --version
    - molecule --version
    - ansible-lint --version
    # Use actual Ansible Galaxy role name for the project directory.
    - cd ../
    # - mv ansible-role-$ROLE_NAME ryandaniels.$ROLE_NAME
    # - cd ryandaniels.$ROLE_NAME
    - ln -s ansible-role-$ROLE_NAME ryandaniels.$ROLE_NAME
    - cd ryandaniels.$ROLE_NAME
  script:
    - molecule test --destroy=never && molecule test --scenario-name second-change
    # - molecule destroy
    # - sleep 3600
  # only:
  #   refs:
  #     - branches
  #     - tags
  #     - merge_requests
  # except:
  #   changes:
  #     - "**/*.{md,rst,gitignore}"
  #     - "meta/*"

molecule-centos7:
  stage: tests
  extends: .molecule_test
  variables:
    MOLECULE_DISTRO: "centos:7"

molecule-centos8:
  stage: tests
  extends: .molecule_test
  variables:
    MOLECULE_DISTRO: "centos:8"

molecule-fedora31:
  stage: tests
  extends: .molecule_test
  variables:
    MOLECULE_DISTRO: "fedora:31"

#much slower but works
# image: docker:git
# services:
#   - docker:dind

# stages:
#   - tests

# before_script:
#   - export ROLE_NAME=firewalld
#   - apk update && apk add --no-cache docker
#     python3-dev py3-pip docker gcc git curl build-base
#     autoconf automake py3-cryptography linux-headers
#     musl-dev libffi-dev openssl-dev openssh
#   - python3 -m pip install ansible molecule docker ansible-lint
#   - docker -v
#   - python3 --version
#   - ansible --version
#   - molecule --version
#   - ansible-lint --version
#   # Use actual Ansible Galaxy role name for the project directory.
#   - cd ../
#   # - mv ansible-role-$ROLE_NAME ryandaniels.$ROLE_NAME
#   # - cd ryandaniels.$ROLE_NAME
#   - ln -s ansible-role-$ROLE_NAME ryandaniels.$ROLE_NAME
#   - cd ryandaniels.$ROLE_NAME

# molecule-centos7:
#   stage: tests
#   script:
#     - export MOLECULE_DISTRO="centos:7"
#     - molecule test --destroy=never && molecule test --scenario-name second-change
#     - molecule destroy

# molecule-fedora31:
#   stage: tests
#   script:
#     - export MOLECULE_DISTRO="fedora:31"
#     - molecule test --destroy=never && molecule test --scenario-name second-change
#     - molecule destroy
