---
image: quay.io/ansible/molecule:latest
services:
  - docker:dind

stages:
  - tests

before_script:
  - export ROLE_NAME=firewalld
  - docker -v
  - python -V
  - ansible --version
  - molecule --version
    # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME ryandaniels.$ROLE_NAME
  - cd ryandaniels.$ROLE_NAME
  - ls -l

molecule-role-firewalld:
  stage: tests
  tags:
    - docker
  variables:
    DOCKER_HOST: "tcp://docker:2375"
    PY_COLORS: 1
  script:
    # - cd roles/firewalld/
    - molecule test
#   only:
#     changes:
#       - roles/common/**/*
