---
language: python
# python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

env:
  global:
    - ROLE_NAME: firewalld
  matrix:
    - MOLECULE_DISTRO: centos7

install:
  # Install ansible
  - pip install ansible ansible-lint 'molecule[docker]'

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME ryandaniels.$ROLE_NAME
  - cd ryandaniels.$ROLE_NAME

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  # - molecule test
  - molecule test --destroy=never && molecule test --scenario-name second-change

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
