---
- name: Prepare
  hosts: all
  tasks:

#Fix for OpenVZ virtualization / custom kernel missing modules needed by firewalld
#source: https://www.getpagespeed.com/server-setup/fix-firewalld-in-centos-7
# MODULES_DIR=/lib/modules/$(uname -r)
# mkdir -p ${MODULES_DIR}
# # touch ${MODULES_DIR}/modules.{builtin,order}
# /bin/truncate --size=0 ${MODULES_DIR}/modules.builtin
# /bin/truncate --size=0 ${MODULES_DIR}/modules.order
# for i in /sys/module/*; do echo kernel/${i##**/}.ko; done >> ${MODULES_DIR}/modules.builtin
# depmod -a

  - name: firewalld | fix OpenVZ virtualization or custom kernel missing kernel modules
    shell: MODULES_DIR=/lib/modules/$(uname -r) && \
          mkdir -p ${MODULES_DIR} && \
          /bin/truncate --size=0 ${MODULES_DIR}/modules.builtin && \
          /bin/truncate --size=0 ${MODULES_DIR}/modules.order && \
          for i in /sys/module/*; do echo kernel/${i##**/}.ko; done >> ${MODULES_DIR}/modules.builtin && \
          depmod -a
    register: cmd
    failed_when: false
    ignore_errors: true
    changed_when: false
    # no_log: True
    when:
  #    - ansible_os_family == "RedHat"
  #    - ansible_distribution_major_version == '7'
      - firewalld_managed|bool
      - ansible_virtualization_type|lower == "docker"
    tags:
      - firewalld
      - firewalld_start

  - name: debug stat_service_firewalld_status
    debug: var=cmd.stdout_lines
    when:
      # - ansible_os_family == "RedHat"
      # - ansible_distribution_major_version == '7'
      - firewalld_managed|bool
      - ansible_virtualization_type|lower == "docker"
      # - debug_enabled_default|bool
    tags:
      - firewalld
      - firewalld_start
