---
- name: Verify
  hosts: all
  tasks:

  - name: Check firewalld running
    command: systemctl status firewalld warn=false
    register: stat_service_firewalld_status
    # ignore_errors: true
    changed_when: false
    # no_log: True
    failed_when: not stat_service_firewalld_status.rc == 0

  # - debug: var=stat_service_firewalld_status

  - name: Check source ip in internal zone
    command: firewall-cmd --permanent --zone=internal --query-source=192.168.22.64/26
    register: cmd
    # ignore_errors: true
    changed_when: false
    failed_when: not cmd.rc == 0

  - name: Check source ip not in internal zone
    command: firewall-cmd --permanent --zone=internal --query-source=192.168.32.64/26
    register: cmd
    # ignore_errors: true
    changed_when: false
    failed_when: not cmd.rc == 1

  - name: Check service created and in public zone
    command: firewall-cmd --permanent --zone=public --query-service=app123-public
    register: cmd
    # ignore_errors: true
    changed_when: false
    failed_when: not cmd.rc == 0

  - name: Check service created and not in internal zone
    command: firewall-cmd --permanent --zone=internal --query-service=app123-public
    register: cmd
    # ignore_errors: true
    changed_when: false
    failed_when: not cmd.rc == 1

  - name: Check port added to custom service
    command: firewall-cmd --permanent --service=app123-public --query-port=5000/tcp
    register: cmd
    # ignore_errors: true
    changed_when: false
    failed_when: not cmd.rc == 0

  - name: Check custom port added to built-in service
    command: firewall-cmd --permanent --service=zabbix-agent --query-port=3333/tcp
    register: cmd
    # ignore_errors: true
    changed_when: false
    failed_when: not cmd.rc == 0

  - name: Check default port not added to built-in service
    command: firewall-cmd --permanent --service=zabbix-agent --query-port=10050/tcp
    register: cmd
    # ignore_errors: true
    changed_when: false
    failed_when: not cmd.rc == 1

  # # Check firewalld running
  # - systemctl status firewalld
  # # Check source ip in internal zone
  # - sudo firewall-cmd --permanent --zone=internal --query-source=192.168.22.64/26
  # # Check source ip not in internal zone
  # - sudo firewall-cmd --permanent --zone=internal --query-source=192.168.32.64/26 || echo "success, not found"
  # # Check service created and in public zone
  # - sudo firewall-cmd --permanent --zone=public --query-service=app123-public
  # # Check service created and not in internal zone
  # - sudo firewall-cmd --permanent --zone=internal --query-service=app123-public || echo "success, not found"

  # # Check port added to custom service
  # - sudo firewall-cmd --permanent --service=app123-public --query-port=5000/tcp

  # # Check custom port added to built-in service
  # - sudo firewall-cmd --permanent --service=zabbix-agent --query-port=3333/tcp
  # # Check default port not added to built-in service
  # - sudo firewall-cmd --permanent --service=zabbix-agent --query-port=10050/tcp || echo "success, not found"

  # # Run the role/playbook again but make change
  # - "ansible-playbook -i tests/inventory tests/test-change.yml --connection=local --become"

  # # Check port not added to custom service when disabled
  # - sudo firewall-cmd --permanent --service=app123-public --query-port=5000/tcp || echo "success, not found"

  # # Check port added to custom service
  # - sudo firewall-cmd --permanent --service=app123-internal --query-port=8089/tcp
  # # Check port not added to custom service when removed from config
  # - sudo firewall-cmd --permanent --service=app123-internal --query-port=8080/tcp || echo "success, not found"
